# Generated by Django 5.2.1 on 2026-05-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_loginlog_delete_failedlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='action',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
